### ISSUE TITLE
Add back MockCT Images

### ISSUE THREAD

**Issue by kmader** [4Quant/COPD-staging#18] opened 2016-01-21 09:07 UTC
The reason the tests failed before is when you renamed the image files you ended up just deleting them. So can you add them back (you can manually add them from the command line with `git add -f`

**Comment by drtjre** [comment] 2016-01-21 12:32
OK.  Have done this, then with R-studio committed/pushed.  You should see them again now.

**Comment by drtjre** [comment] 2016-01-21 12:54
Just checked and images were not on github:(.  I then tried to repeat, this time specifying also the directory name - no luck, but did get this error:

To https://github.com/4Quant/COPD-staging.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/4Quant/COPD-staging.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.

**Comment by drtjre** [comment] 2016-01-21 12:55
will try git pull first ...

**Comment by kmader** [comment] 2016-01-21 13:08
Always run `git pull` to get any changes before you commit changes to avoid issues.

**Comment by drtjre** [comment] 2016-01-21 13:12
OK - just did the following which worked.

`git pull`
`git add -f mockCTs/*.tif`
`git commit`
`git push`

**Comment by drtjre** [comment] 2016-01-21 13:16
All online:
(https://github.com/4Quant/COPD-staging/tree/master/src/test/resources/mockCTs)

**Closed as completed by drtjre** 2016-01-21 13:16 UTC
Labels: bug
